### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [woheller69/whoBIRD#117]
https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/11268924700

Could you please take a look? And could you please pin the version of the new dep? Thanks!

**Comment by woheller69** [comment]
Strange.

    implementation 'com.github.woheller69:FreeDroidWarn:+

always takes the latest version. Does F-Droid build not support that?

**Comment by linsui** [comment]
It's supported but would break reproducible build.

**Comment by woheller69** [comment]
I do not use reproducible build

**Comment by linsui** [comment]
F-Droid also checks if the apk can be rebuild after a while. https://verification.f-droid.org/packages/org.woheller69.whobird/ And a dynamic version may break the build in the future.

**Comment by woheller69** [comment]
So it is NOT supported by F-Droid...

Then  I will need to create new releases for several apps

**Comment by linsui** [comment]
It's not encouraged. And the build failed due to some other issues.

**Comment by woheller69** [comment]
seem I forgot to commit a change in settings.gradle 

Will create new version

**Comment by woheller69** [comment]
done

**Comment by licaon-kter** [comment]
Still fails https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/11268924700

**Comment by linsui** [comment]
Thanks!
